language: ruby
cache: bundler
rvm:
- 2.1

install: gem install jekyll html-proofer jekyll-redirect-from
script: jekyll build && htmlproofer --check-html --only-4xx ./_site

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

sudo: false
